#!/bin/bash

#Function to display the usege of options

usage() {

    echo "Usage: $0 -u username -p password -s shell -h home_dir -g groups"
    echo " -u username Type username for th enew user"
    echo " -p password: THe password for the new user"
    echo " -s shell: The login shell for the new user"
    echo " -h home_dir: Home directory for the new user"
    echo " -g groups : Groups for the new user"
    exit 1


}



#Variables for options
#These options are needed, so we can control the user creation

username=""

password=""

shell="/bin/bash"

home_dir=""

groups=""
#Options created so we can parse the options to the command line

while getopts ":u:p:s:h:" opt; do
     case "${opt}" in
	#The first case, this case handles the username option
	u)
	  username=${OPTARG}
	  ;;
	#The second case handles the user password
	p)
	  password=${OPTARG}
	  ;;
	#This case handles the shell, in this script the default shell is atuomatiacally assigned to variables, so it will always default to it
  	s)
	  shell=${OPTARG}
	  ;;
	#This case hadnles a creation of the hoem directory
  	h)
	  home_dir=${OPTARG}
	  ;;
	#This case handles additional groups  
	g)
	#This case handles every ohter case, it will inform a user that there has been an error. 
	#Usage funciton is called, and it will display all the possible options for the user
	*)
	  echo "That is not a valid option $OPTARG"
	  usage
	  ;;
     esac
done

#This if statement checks if the string is empty.
#Then prompots the user to enter a new username
if [[ -z $username ]]; then
    read -p "Enter your username" username 
fi

#This if statement checks if the password is empty, then asks user to create a new password. 
#Using passwd utility the user will create a new password for the new user
if [[ -z $password ]]; then

     read -p "Create a new user password: " password
     passwd $username
     echo "Password succesfully created"
fi

#This statement creates a new shell.
#In this script the shell is set to default #!/bin/bash
if [[ -z $shell ]]; then
    read -p "Press enter to create to create your shell" shell
fi

#This if statement checks if the hom_dir variable is empty
#Then creates a new home directory
#After that the content of the etc/skel directory will be copied to the new home directory
#/. will ensure to copied all the files, including hidden files
if [[ -z $home_dir ]]; then
    
    #Informing the user about the current status
    echo "Creating home directory $home_dir"
    #Creating a home directory
    mkdir -p "$home_dir"
    home_dir="/home/$username"
    
    #Coping the /etc/skel to our newly created home directory
    cp -r /etc/skel/. home_dir
    #Changong ownership on the home directory
    chown "$username" "$home_dir"

fi

#Creating primary group for the newly created user
primary_group=$username

if [[ -z $groups ]]; then
    read -p "Type the additional groups for the user" groups
fi

#Additional groups
if [[ -n $groups ]]; then
     
     #This will add groups to the list of groups
     #IFS will seprate them by commas
     IFS="," read -r -a list_of_groups <<< "$groups"
     
     #looping through the list of groups 
     for group in "${list_of_groups[@]}"; do
	
     #This if statement will check if the group exist in /etc/group dir
     #If the user exist the user will be added to the group
     if grep -q "^group:" /etc/group; then
	
	sed -i "/^group:/ s/$/,username/" /etc/group

     #If the group does not exist the else statement will be executed
     #The group will be created 
     #And the new user will be added
     else
	#New gid created
	
	new_gid+$(($(tail -n  /etc/group | cut -d: -f3) +1













