#!/bin/bash



#Packages path assigned to a variable assigned to a varibles
kakoune="/home/arch/Assignment_2/config/kak/kakrc"
tmux="/home/arch/Assignment_2/config/tmux/tmux.conf"


#Symbolic links stored in new a varibales

kakoune1="~/.config/kakrc"
tmux1="~/.config/tmux.conf"

#Printing the messages for the user so it can see what packages needs to install
echo "These are teh packages that you need to install:"
echo "kakoune"
echo "tmux"

#Asking user to choose which package the user watns to install - refernces are class note
read -p "Please Type letter A to install kakoune package or type letter B to install tmux package: "

#Using options to install the package, the user can choose an optoion as they wish. by doing that it will activate the selected options.
#The asterix means any other case besides the a,b, or c. Any other message will provide an error message and the user will be informed that needs to chooe something else
while getopts "a:b:c:" opt; do
  case "${opt}" in
    a | A)
        echo "Kakaoune package is installing..."
        kakoune1=${OPTARG}
        exit 0
        ;;
      
    b | B)
        echo "Tmux package is installing"
        tmux=${OPTARG}
       ;;
    c | C)
        echo "Installing both packages"
        ;;

    *)
      echo "You have entered something else"
      exit 1
      ;;
  esac
done

if [[ -n $kakoune1 ]]; then
  pacman -S kakrc
  echo "package sucessfully installed"
fi

#if [[ -n $tmux ]]; then
 # pacman -U "$tmux"
#fi
