#!/bin/bash


#Request from the user to use their sudo privilages before runnign the script
if [[ "$EUID" -ne 0 ]]; then
    echo "You have to run this script as a root user!"
    exit 1
fi

#Packages file assigned to a varibles
kakoune="/home/arch/Assignment_2/config/kak/kakrc"
tmux="/home/arch/Assignment_2/config/tmux/tmux.conf"

#Create the .config and bin directories
mkdir -p ~/.config
mkdir -p ~/bin

#creating symbolic links
ln -s "/home/arch/Assignment_2/config/kak/kakrc" "~/.config/kak"
#ln -s /home/arch/Assignment_2/config/tmux/tmux.conf ~/.config/tmux.conf

kakoune1="/.config/kakrc"

#Printing the messages for the user so it can see what packages needs to install

echo "These are teh packages that you need to install:"
echo "kakoune"
echo "tmux"

read -p "Please Type letter A to install kakoune package or type letter B to install tmux package: "


while getopts "a:" opt; do
  case "${opt}" in
    a | A)
        echo "package is installing..."
        kakoune1=${OPTARG}
        exit 0
        ;;
      
  #  b | B)
   #     tmux=${OPTARG}
    #   ;;
    *)
      echo "You have entered something else"
      exit 1
      ;;
  esac
done

if [[ -n $kakoune1 ]]; then
  pacman -S 
  echo "package sucessfully installed"
fi

#if [[ -n $tmux ]]; then
 # pacman -U "$tmux"
#fi
