#!/bin/bash

#The packages are stored in a variable.
#This way packages are easier to handle for installation and error handling

packages=("kakoune" "tmux")

#Prinitng all the packages that need to be installed
echo "These packages will be installed: ${packages[@]}"


#Create a function in order to handle the installation packages 
package_installation() {

    #Using the for loop to loop through the packages varibale
    for package in  "${packages[@]}"; do 

	#This if statement will check if the any of the packages are installed already.
	if ! pacman -Q "$package"; then
		#Informing the user what is the current status
		echo "You packages are getting installed"
		#installing the packages using pacman
		pacman -S $package
        
	#This else statement will get executed if the packages have been already installed
	#The error code will be send to the system as well exit code 1
	else
	      echo "The packages have been installed already"
	fi
    done

}



package_installation

