#!/bin/bash

#This command will request from user to run the main script as a root user, 
#that means the user has to use the sudo command in order to run the script. 
#As we did not looked up this command in class. 
#Reference:https://tecadmin.net/check-if-a-script-is-running-as-root-user-in-linux/


if [[ "$EUID" -ne 0 ]]; then
    echo "You have to run this script as a root user!"
    exit 1
fi


#Paths to the two scripts - they are in the same directory so this is sufficent
PACKAGES="./install_packages"
DOTFILES="./dotfiles"

#Chaning premsion on the both of the scripts, ensuring that both scripts can run
chmod +x "$PACKAGES"
chmod +x "$DOTFILES"

#This function will install the packages

install_packages() {
     echo "Instalation started" 
     "$PACKAGES"

     #If the exit code is 0, then the instalation was succefull
     if [[ $? -eq 0 ]]; then
	echo "Packages installed successfully"
     
     #Otherwise the esle satement will be excuted
     #And it will inform the user about an error
	else
	    echo "Packages instalation failed" >&2
	    exit 1
     fi	    
}

#This function will run the dotfiles script, and create symbolic links

dotfiles() {

     echo "Creating Symbolic Links" 
     "$DOTFILES"

     #If the exit code is equal to 0, the symbolic links are created successfully
     if [[ $? -eq 0 ]]; then
	echo "Symbolic links created"

     #Otherwise if the exit code is diffrent than 0
     #The else statement will be executed, and it will send an error message to the user
     else
	echo "Symbolic link creation failed" >&2
	exit 1
     fi

}

#Using getopts to proivde user options
#The user can install only packages or only symbolic links
#It can do both, by choosing a third option
#If user does not choose any of the options, 
#It will be prompt again to choose one of the 3 options

while getopts "psa" opt; do
	case "${opt}" in
	#For the instalation of the packages is the option p
	#If this option is choosen the install_packages function will be called
	    p)
              install_packages
	      ;;
	#For the creation of the symbolic links is option s
	#If this option is choosen, the dotfiles function will be called
	    s)
              dotfiles
	      ;;
	#Option a will run both scripts if choosen
	#Both function dotfiles and install_packages will be called
	    a)
	      install_packages
              dotfiles
	      ;;
	#This option handles all the other cases,
	#If the user choose anything else except the 3 options above
	#The message will be sent to the user what are valid / possible options

	    *) 
	      #Informing user about teh possible options that should be used
	      #$0 shows the name of the scripts( the main script)
	      #Other options are what user shoudl choose
	      echo "Use $0 [-p] [-s] [-a]"
	      echo "Choose -p to install the packages"
	      echo "Choose -s to create symbolic links"
	      echo "CHoose -a to install packages and to create symbolic links"
	      exit 1
	      ;;
	esac
done

#If the user did not proivde any input, 
#Additional check will chjeck will be done
#The message will inform the user about the possible options

if [[ $OPTIND -eq 1 ]]; then
	echo "Use: $0 [-p] [-s] [-a]"
	echo "Choose -p to install the packages"
	echo "Choose -s to create symbolic links"
        echo "Choose -a to install packages and to create symbolic links"
	exit 1
fi

echo "Everything went well"
