#!/bin/bash

#User nees to run the script as root(sudo user)

if [[ "$EUID" -ne 0 ]]; then
     echo "Please run this script as root user"
     exit 1
fi

#Function to display the usege of options
usage() {

    echo "Usage: $0 -u username -s shell -h home_dir -g groups"
    echo " -u username Type username for the new user"
    echo " -s shell: Type the login shell for the new user if none it will default to /bin/bash"
    echo " -h home_dir: Type the home directory for the new user"
    echo " -g groups : Choose groups for the new user"
    exit 1

}


#Variables for options
#These options are needed, so we can control the user creation

username=""

shell="/bin/bash"

home_dir=""

groups=""

#Options created so we can parse the options to the command line
while getopts ":u:s:h:g:" opt; do
     case "${opt}" in
	#The first case, this case handles the username option
	u)
	  username=${OPTARG}
	  ;;
       s)
	  shell=${OPTARG}
	  ;;
	#This case hadnles a creation of the hoem directory
       h)
	  home_dir=${OPTARG}
	  ;;
	#This case handles additional groups  
       g)
	#This case handles every ohter case, it will inform a user that there has been an error. 
	#Usage funciton is called, and it will display all the possible options for the user
	  groups=${OPTARG}
	  ;;
       *)
	  echo "That is not a valid option ${OPTARG}"
	  usage
	  ;;
     esac
done

#This if statement checks if the string is empty.
#Usage function will be called, and it will show possible options for the user

if [[ -z $username ]]; then
    usage
fi

#This if statement checks if the home_dir variable is empty
#And it will set default home idrectory
if [[ -z $home_dir ]]; then
    home_dir="/home/$username"	
fi

#This if statement creates a new home directory
#After that the content of the etc/skel directory will be copied to the new home directory
#/. will ensure to copied all the files, including hidden files
if [[ ! -d $home_dir ]]; then

    #Informing the user about the current status
    echo "Creating home directory $home_dir"
    #Creating a home directory
    mkdir -p "$home_dir"
    #Coping the /etc/skel to our newly created home directory
    cp -r /etc/skel/. "home_dir"
    
fi

#This statement creates a new shell.
#In this script the shell is set to default #!/bin/bash

if [[ -z $shell ]]; then
    read -p "Enter the login shell for the new user: " shell
    shell="${shell:-/bin/bash}"  
fi

#Creating primary group for the newly created user

gid=$(($(tail -n 1 /etc/group | cut -d: -f3) + 1))
echo "$username:x:$gid:" | tee -a /etc/group 


#Creating an user id and primary group id

uid=$(($(tail -n 1 /etc/passwd | cut -d: -f3) + 1))
gid=$uid

#Adding user a user entry to the etc/passwd file

echo "$username:x:$uid:$gid:$username:$home_dir:$shell" | tee -a /etc/passwd 
 

#Additional groups

if [[ -n $groups ]]; then
     
     #This will add groups to the list of groups
     #IFS will seprate them by commas
     IFS="," read -r -a list_of_groups <<< "$groups"
     
     #looping through the list of groups 
     for group in "${list_of_groups[@]}"; do
	
     #This if statement will check if the group exist in /etc/group
     #If the group exist the user will be added to the group
     if  grep -q "^$group:" /etc/group; then
         sed -i "/^$group:/ s/$/,$username/" /etc/group
	
     #If the group does not exist the else statement will be executed
     #It will find the highest gid and increment by 1 for the new group
     else 
     	
	new_gid=$(( $( tail -n 1 /etc/group | cut -d: -f3 ) + 1 ))
	#writing to the /etc/group file      
	cat >> /etc/group <<- END
	    $group:x:$new_gid:$username
	END
     fi 
 done

fi

#Informing user that the process is finished
echo "User $username successfully created"


#Creating a new password for the user
passwd $username

