#!/bin/bash

#The condition belown will check if the /.config and /bin directories exist.
#If the directories exist it will send an error message tot the user and the exit 1 it will signal the user that there is an error.
#Otherwise if the directories do not exist it the else statement will execute and the directiores will be created.
#The statement ends with a message for the user that directiores are created succesfully

if [[ -d ~/.config/kak && -d ~/bin/tmux ]]; then
  echo "This direcorty exist alredy"
else
  mkdir -p ~/.config/kak
  mkdir -p ~/.config/tmux
  mkdir -p ~/bin
  echo "Directories are created succesfully"

fi


#Reference: https://realtechtalk.com/bash_how_to_check_if_a_symlink_exists_as_a_file_or_directory-1843-articles
#This if statement will check if the symbolic links with the mentioned paths exists. 
#if it they exists the user will recive a message that the symbolic link already exist, 
#Otherwise the ele statement will execute and it will create a new symbolic links.
#The user wil recive a meesage about the status and if everything went ok , the success message will be printed to the console.

if [[ -L ~/.config/kak && -L ~/.config/tmux && -L ~/.bashrc && -L ~/bin ]]; then
    echo "The symbolic links are created already"
else
    ln -s ~/home/arch/Assignment_2/config/kak ~/.config/kak
    ln -s ~/home/arch/Assignment_2/config/tmux/tmux.conf ~/.config/tmux
    ln -s ~/home/basrc /.bashrc
    ln -s ~/home/arch/Assignment_2/bin ~/bin
    echo "Symbolic links succesfully created"
fi

